AWSTemplateFormatVersion: 2010-09-09

# Distribuzione CloudFront

# Infrastruttura
# ===============
# CloudFront:
#   Origini:
#     - ALB:
#       - Porta HTTP: 80
#       - Origin protocol policy: http-only
#       - Origin custom headers: X-Origin-CloudFront-Only (vedi ALB)
#       - Domain name: ALB domain name

Parameters:
  # Valori ammessi:
  # PriceClass_100 -> USA, Canada, Europe, & Israel
  # PriceClass_200 -> PRICE_CLASS_100 + South Africa, Kenya, Middle East, Japan, Singapore,
  #                   South Korea, Taiwan, Hong Kong, & Philippines
  # PriceClass_300 -> All locations
  CloudFrontPriceClass:
    Description: Classe di prezzo della distribuzione CloudFront
    Type: String
    AllowedValues:
      - "PriceClass_100"
      - "PriceClass_200"
      - "PriceClass_All"

Resources:
  # VPC Origin
  CloudFrontVPCOrigin:
    Type: AWS::CloudFront::VpcOrigin
    Properties:
      VpcOriginEndpointConfig:
        Arn: !Ref ALB
        HTTPPort: 80
        Name: !Sub "${AWS::StackName}-CloudFrontVPCOrigin"
        # Il load balancer non è configurato con HTTPS
        OriginProtocolPolicy: http-only
      Tags:
        - Key: EnvType
          Value: !Ref EnvType

  # Distribuzione CloudFront
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # NOTA: da configurare qualora si voglia usare il proprio nome di dominio
        # Aliases:
        #  - example.com
        Comment: CloudFront distribution
        DefaultCacheBehavior:
          # Valori ammessi:
          # - GET, HEAD
          # - GET, HEAD, OPTIONS
          # - GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          # Valori ammessi:
          # - GET, HEAD
          # - GET, HEAD, OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          # UseOriginCacheControlHeaders
          # Id: 83da9c7e-98b4-4e11-a168-04f0df8e2c65
          # MinTTL: 0
          # MaxTTL: 365 giorni
          # Default TTL: 0
          # Header inclusi:
          # - Accept-Encoding
          # - Host
          # - Origin
          # - X-HTTP-Method
          # - X-HTTP-Method-Override
          # - X-Method-Override
          # Cookie inclusi: tutti
          # Query strings incluse: nessuna
          #
          # UseOriginCacheControlHeaders-QueryStrings
          # Id: 4cc15a8a-d715-48a4-82b8-cc0b614638fe
          # MinTTL: 0
          # MaxTTL: 365 giorni
          # Default TTL: 0
          # Header inclusi:
          # - Accept-Encoding
          # - Host
          # - Origin
          # - X-HTTP-Method
          # - X-HTTP-Method-Override
          # - X-Method-Override
          # Cookie inclusi: tutti
          # Query strings incluse: tutte
          CachePolicyId: 4cc15a8a-d715-48a4-82b8-cc0b614638fe
          # Origin request policy
          # ======================
          # AllViewer
          # Id: 216adef6-5c7f-47e4-b989-5492eafa07d3
          # Header inclusi: tutti quelli della richiesta viewer
          # Cookie inclusi: tutti
          # Query strings incluse: tutte
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          #PathPattern: "*"
          TargetOriginId: VPCOrigin
          # Valori ammessi:
          # allow-all -> Permetti sia HTTP che HTTPS
          # redirect-to-https -> HTTP viene reindirizzato ad HTTPS
          # https-only -> Solo HTTPS; HTTP risponde con un codice 403
          ViewerProtocolPolicy: redirect-to-https
        # DefaultRootObject:
        Enabled: true
        # Valori ammessi:
        # http1.1 -> HTTP/1.1
        # http2 -> Solo HTTP/2
        # http3 -> Solo HTTP/3/QUIC
        # http2and3 -> HTTP/2 e HTTP/3 (Richiede >TLSv1.3 per l'origine)
        HttpVersion: http1.1
        # Abilita supporto per IPv6
        #IPV6Enabled: true
        Logging:
          Bucket: !GetAtt S3Bucket.DomainName
          IncludeCookies: true
          Prefix: "logs/cloudfront/"
        Origins:
          - Id: VPCOrigin
            VpcOriginConfig:
              VpcOriginId: !GetAtt CloudFrontVPCOrigin.Id
            # Nome di dominio dell'origine
            # Usiamo il nome del Load Balancer
            DomainName: !GetAtt ALB.DNSName
        PriceClass: !Ref CloudFrontPriceClass
      Tags:
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  CFDomainName:
    Description: CloudFront Domain Name
    Value: !GetAtt CloudFront.DomainName
