AWSTemplateFormatVersion: 2010-09-09

# Gestione dei segreti

Resources:
  # Username da usare sul DB RDS
  DBUsernameSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Password del DB RDS
      # Genera un nuovo username casuale
      GenerateSecretString:
        # Non includere numeri
        ExcludeNumbers: true
        # Non includere punteggiatura
        ExcludePunctuation: true
        # Non includere caratteri maiuscoli
        ExcludeUppercase: true
        # Non includere spazi
        IncludeSpace: false
        # Lunghezza: 16 caratteri (max per MariaDB)
        PasswordLength: 16
      KmsKeyId: !Ref RDSKMSKey
      Name: !Sub "${AWS::StackName}-DBUsernameSecret"
      Tags:
        - Key: EnvType
          Value: !Ref EnvType

  # Password da usare sul DB RDS
  # Lunghezza standard: 32 caratteri
  DBPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Password del DB RDS
      # Genera una nuova password casuale
      GenerateSecretString:
        # Non includere ", @, /, \
        ExcludeCharacters: '"@/\'
        # Non includere spazi
        IncludeSpace: false
      KmsKeyId: !Ref RDSKMSKey
      Name: !Sub "${AWS::StackName}-DBPasswordSecret"
      Tags:
        - Key: EnvType
          Value: !Ref EnvType
